from __future__ import annotations

from pathlib import Path
from typing import Any


BANNED_VISIBLE_PHRASES = [
    "replace this",
    "sample error state",
    "local sample data",
    "adapt this item",
    "placeholder included",
    "generated by forgetrend",
    "core flow",
    "next action",
    "review the first workflow",
]

VIETNAMESE_MARKERS = [
    "học",
    "ứng dụng",
    "tiến độ",
    "hôm nay",
    "cài đặt",
    "quyền riêng tư",
    "mô phỏng",
    "bắt đầu",
]

TRADEMARK_TERMS = ["instagram", "tiktok", "spotify", "netflix", "whatsapp", "uber", "airbnb"]


def _read_texts(root: Path, pattern: str) -> list[tuple[Path, str]]:
    if not root.exists():
        return []
    texts: list[tuple[Path, str]] = []
    for path in root.glob(pattern):
        if path.is_file():
            try:
                texts.append((path, path.read_text(encoding="utf-8")))
            except UnicodeDecodeError:
                continue
    return texts


def _has_any(text: str, values: list[str]) -> bool:
    lowered = text.lower()
    return any(value.lower() in lowered for value in values)


def build_quality_gate_result(
    *,
    project: dict[str, Any],
    app_dir: Path,
    artifacts: list[dict[str, Any]],
    brief: dict[str, Any] | None,
    qa_output: dict[str, Any] | None,
    policy_output: dict[str, Any] | None,
) -> dict[str, Any]:
    lib_texts = _read_texts(app_dir / "lib", "**/*.dart")
    test_texts = _read_texts(app_dir / "test", "**/*.dart")
    combined_lib = "\n".join(text for _, text in lib_texts)
    combined_all = "\n".join(text for _, text in [*lib_texts, *test_texts])
    target_language = str((brief or {}).get("target_language") or "en").lower()
    threshold = int((brief or {}).get("quality_threshold") or 75)

    issues: list[str] = []
    required_changes: list[str] = []

    banned_hits = [
        phrase
        for phrase in BANNED_VISIBLE_PHRASES
        if phrase in combined_lib.lower()
    ]
    if banned_hits:
        issues.append(f"Generic placeholder copy found: {', '.join(banned_hits)}")
        required_changes.append("Replace all visible generic template copy with product-specific wording.")

    screen_count = len(list((app_dir / "lib" / "features").glob("**/*_screen.dart"))) if (app_dir / "lib" / "features").exists() else 0
    if screen_count < 5:
        issues.append(f"Only {screen_count} feature screen(s) found.")
        required_changes.append("Keep onboarding, home, core feature, progress/history, settings, privacy, and paywall when configured.")

    has_tests = bool(test_texts) and _has_any(combined_all, ["testWidgets", "onboarding", "settings"])
    if not has_tests:
        issues.append("Generated app tests are missing or too thin.")
        required_changes.append("Add widget tests for onboarding, core feature, settings/privacy, and paywall when enabled.")

    has_privacy = (app_dir / "PRIVACY_POLICY.md").exists() or _has_any(combined_lib, ["quyền riêng tư", "privacy"])
    if not has_privacy:
        issues.append("Privacy/about surface is missing.")
        required_changes.append("Add a privacy/about screen and privacy policy draft.")

    has_vietnamese = _has_any(combined_lib, VIETNAMESE_MARKERS)
    if target_language == "vi" and not has_vietnamese:
        issues.append("Vietnamese UI copy was requested but not found.")
        required_changes.append("Generate Vietnamese app strings and use Vietnamese as the default app language.")

    has_static_cards_only = "StatusCard(" in combined_lib and not _has_any(
        combined_lib,
        ["ListView.builder", "CheckboxListTile", "showDialog", "SnackBar", "LinearProgressIndicator", "progress"],
    )
    if has_static_cards_only:
        issues.append("Core feature appears too static.")
        required_changes.append("Add an interactive product-specific flow with state changes and feedback.")

    has_apk = any(item.get("kind") == "build" or str(item.get("name", "")).endswith(".apk") for item in artifacts)
    if "android" in [str(item).lower() for item in project.get("target_platforms", [])] and not has_apk:
        issues.append("Android target is configured but APK artifact is missing.")
        required_changes.append("Run Flutter Android build successfully before release-candidate status.")

    if _has_any(combined_all, ["sk-", "api_key", "private_key"]):
        issues.append("Potential secret marker found in generated source.")
        required_changes.append("Remove all hardcoded credentials and secret-like markers.")

    if _has_any(project.get("name", ""), TRADEMARK_TERMS):
        issues.append("Project name may include a protected brand.")
        required_changes.append("Rename the generated app with original branding.")

    if _has_any(combined_lib, ["auto publish", "published to google play", "published to app store"]):
        issues.append("Generated app makes misleading publishing claims.")
        required_changes.append("Remove any claim that the app is already published or store-approved.")

    has_journey = _has_any(
        combined_lib,
        ["OnboardingScreen", "CheckboxListTile", "showDialog", "SnackBar", "history", "SettingsScreen", "PrivacyScreen"],
    ) and screen_count >= 6
    if not has_journey:
        issues.append("Main user journey is incomplete.")
        required_changes.append("Add Start -> Input/Select -> Process/Review -> Result/Progress -> History/Settings.")

    store_asset_names = {str(item.get("name", "")).lower() for item in artifacts}
    has_store_assets = any("short_description" in name for name in store_asset_names) and any("screenshot_plan" in name for name in store_asset_names)
    if not has_store_assets:
        issues.append("Store asset drafts are missing.")
        required_changes.append("Generate store title, descriptions, keywords, privacy summary, and screenshot checklist drafts.")

    minimum_functionality_score = 90 if screen_count >= 6 and not has_static_cards_only else 65 if screen_count >= 5 else 45
    ux_completeness_score = 90 if has_privacy and has_tests and screen_count >= 6 else 70 if has_privacy and has_tests else 45
    localization_score = 95 if target_language != "vi" or has_vietnamese else 40
    store_readiness_score = 90 if has_apk and has_store_assets and not banned_hits and not _has_any(combined_all, ["sk-"]) else 55
    product_specificity_score = 92 if not banned_hits and len(project.get("name", "")) >= 5 else 55
    user_journey_clarity_score = 90 if has_journey else 50
    feature_depth_score = 90 if screen_count >= 7 and not has_static_cards_only else minimum_functionality_score
    monetization_clarity_score = 85 if _has_any(combined_lib, ["Premium", "Gói Premium", "productionBillingEnabled", "Mô phỏng thanh toán"]) else 70
    policy_safety_score = 95 if not policy_output or policy_output.get("passed") else 55
    technical_quality_score = 90 if qa_output and qa_output.get("passed") else 55
    generic_template_risk = "high" if banned_hits else ("medium" if has_static_cards_only else "low")
    score = round(
        (
            product_specificity_score
            + user_journey_clarity_score
            + feature_depth_score
            + ux_completeness_score
            + localization_score
            + monetization_clarity_score
            + store_readiness_score
            + policy_safety_score
            + technical_quality_score
        )
        / 9
    )
    if generic_template_risk == "high":
        score = min(score, 60)
    if policy_output and policy_output.get("passed") is False:
        score = min(score, 65)
    if qa_output and qa_output.get("passed") is False:
        score = min(score, 65)

    return {
        "score": score,
        "threshold": threshold,
        "passed": score >= threshold and not required_changes,
        "minimum_functionality_score": minimum_functionality_score,
        "product_specificity_score": product_specificity_score,
        "user_journey_clarity_score": user_journey_clarity_score,
        "feature_depth_score": feature_depth_score,
        "ux_completeness_score": ux_completeness_score,
        "localization_score": localization_score,
        "monetization_clarity_score": monetization_clarity_score,
        "store_readiness_score": store_readiness_score,
        "policy_safety_score": policy_safety_score,
        "technical_quality_score": technical_quality_score,
        "journey_gate_passed": has_journey,
        "aso_growth_gate_passed": has_store_assets,
        "generic_template_risk": generic_template_risk,
        "target_language": target_language,
        "screen_count": screen_count,
        "issues": issues,
        "required_changes": required_changes,
    }


def quality_gate_report_markdown(result: dict[str, Any]) -> str:
    issues = result.get("issues") or ["No blocking product quality issues found."]
    required = result.get("required_changes") or ["No required quality changes before human review."]
    return "\n".join(
        [
            "# Product Quality Gate",
            "",
            f"Score: {result.get('score')}/{100}",
            f"Threshold: {result.get('threshold')}",
            f"Passed: {result.get('passed')}",
            f"Generic template risk: {result.get('generic_template_risk')}",
            f"Feature screens: {result.get('screen_count')}",
            "",
            "## Score Breakdown",
            f"- Product specificity: {result.get('product_specificity_score')}",
            f"- User journey clarity: {result.get('user_journey_clarity_score')}",
            f"- Feature depth: {result.get('feature_depth_score')}",
            f"- Minimum functionality: {result.get('minimum_functionality_score')}",
            f"- UX completeness: {result.get('ux_completeness_score')}",
            f"- Localization: {result.get('localization_score')}",
            f"- Monetization clarity: {result.get('monetization_clarity_score')}",
            f"- Store readiness: {result.get('store_readiness_score')}",
            f"- Policy safety: {result.get('policy_safety_score')}",
            f"- Technical quality: {result.get('technical_quality_score')}",
            "",
            "## Journey and ASO Gates",
            f"- Journey gate passed: {result.get('journey_gate_passed')}",
            f"- ASO/growth gate passed: {result.get('aso_growth_gate_passed')}",
            "",
            "## Issues",
            *[f"- {item}" for item in issues],
            "",
            "## Required Changes",
            *[f"- {item}" for item in required],
        ]
    )


def store_readiness_report_markdown(
    *,
    project: dict[str, Any],
    result: dict[str, Any],
    policy_output: dict[str, Any] | None,
) -> str:
    policy_risk = (policy_output or {}).get("risk", "unknown")
    issues = result.get("issues") or ["No obvious store-readiness blockers found in automated checks."]
    required = result.get("required_changes") or ["Human approval is still required before any store submission."]
    return "\n".join(
        [
            "# Store Readiness Report",
            "",
            f"App name: {project.get('name')}",
            f"Target platform: {', '.join(project.get('target_platforms') or ['android'])}",
            f"Policy risk: {policy_risk}",
            f"Minimum functionality score: {result.get('minimum_functionality_score')}",
            f"Privacy risk: {'low' if result.get('ux_completeness_score', 0) >= 70 else 'medium'}",
            f"IAP/subscription risk: human-reviewed billing setup required when monetization is enabled",
            f"Trademark/copycat risk: {'medium' if any(term in str(project.get('name', '')).lower() for term in TRADEMARK_TERMS) else 'low'}",
            "",
            "## Required Fixes",
            *[f"- {item}" for item in required],
            "",
            "## Recommended Store Listing",
            f"Title: {project.get('name')}",
            "Short description: A focused, privacy-aware mobile workflow built for one clear user goal.",
            "Long description draft: Review and rewrite this with human product judgment before store submission.",
            "",
            "## Screenshot Checklist",
            "- Onboarding",
            "- Home dashboard",
            "- Core feature flow",
            "- Progress/history",
            "- Settings and privacy",
            "- Paywall or premium explanation when configured",
            "",
            "## Human Approval Checklist",
            "- Review all product copy and screenshots.",
            "- Confirm privacy policy accuracy.",
            "- Configure real billing only through StoreKit/Google Play Billing.",
            "- Confirm no trademark or clone risk.",
            "- Do not auto-publish from ForgeTrend.",
            "",
            "## Automated Issues",
            *[f"- {item}" for item in issues],
        ]
    )
