import 'package:flutter/material.dart';

import '../../core/app_content.dart';

class PrivacyScreen extends StatelessWidget {
  const PrivacyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Privacy and about')),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          Text(AppContent.appName, style: Theme.of(context).textTheme.headlineSmall),
          const SizedBox(height: 12),
          const Card(
            child: ListTile(
              leading: Icon(Icons.verified_user_outlined),
              title: Text('Local-first MVP'),
              subtitle: Text('No production analytics, ads, or secrets are included in this scaffold.'),
            ),
          ),
          const SizedBox(height: 12),
          const Card(
            child: ListTile(
              leading: Icon(Icons.policy_outlined),
              title: Text('Privacy policy'),
              subtitle: Text('Replace the placeholder policy before any store submission.'),
            ),
          ),
          const SizedBox(height: 12),
          const Card(
            child: ListTile(
              leading: Icon(Icons.info_outline),
              title: Text('About'),
              subtitle: Text('Generated by ForgeTrend as an original app starting point.'),
            ),
          ),
        ],
      ),
    );
  }
}
