import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const workspaceRoot = path.join(root, "workspaces");
const banned = [
  "replace this",
  "sample error state",
  "local sample data",
  "adapt this item",
  "placeholder included",
  "generated by forgetrend",
  "core flow",
  "next action",
  "review the first workflow",
];

function walk(dir, predicate = () => true) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return walk(full, predicate);
    return predicate(full) ? [full] : [];
  });
}

const candidates = fs.existsSync(workspaceRoot)
  ? fs.readdirSync(workspaceRoot, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => path.join(workspaceRoot, entry.name))
      .filter((dir) => fs.existsSync(path.join(dir, "app", "lib")))
  : [];

if (!candidates.length) {
  console.log("No generated app workspace found; run WORKER_ENABLE_CODEX=false pnpm e2e:factory:vi first.");
  process.exit(0);
}

const v2Candidates = candidates.filter((dir) => fs.existsSync(path.join(dir, "artifacts", "app_blueprint.json")));
if (!v2Candidates.length) {
  console.log("No V2 generated app workspace found; run WORKER_ENABLE_CODEX=false pnpm e2e:factory:vi first.");
  process.exit(0);
}

const latest = v2Candidates.sort((a, b) => fs.statSync(b).mtimeMs - fs.statSync(a).mtimeMs)[0];
const appDir = path.join(latest, "app");
const artifactsDir = path.join(latest, "artifacts");
const dartText = walk(path.join(appDir, "lib"), (file) => file.endsWith(".dart")).map((file) => fs.readFileSync(file, "utf8")).join("\n").toLowerCase();
const missing = [];

for (const phrase of banned) {
  if (dartText.includes(phrase)) missing.push(`banned phrase found: ${phrase}`);
}

for (const required of ["app_blueprint.json", "product_score_report.json"]) {
  if (!fs.existsSync(path.join(artifactsDir, required))) missing.push(`missing ${required}`);
}

const storeDir = path.join(artifactsDir, "store_assets");
for (const required of ["short_description.vi.md", "long_description.vi.md", "screenshot_plan.md", "keywords.md", "privacy_summary.md"]) {
  if (!fs.existsSync(path.join(storeDir, required))) missing.push(`missing store asset ${required}`);
}

const screenCount = walk(path.join(appDir, "lib", "features"), (file) => file.endsWith("_screen.dart")).length;
if (screenCount < 6) missing.push(`expected at least 6 screens, found ${screenCount}`);
if (!["ứng dụng", "tiến độ", "cài đặt", "quyền riêng tư"].some((marker) => dartText.includes(marker))) missing.push("Vietnamese strings not found");
if (!dartText.includes("checkboxlisttile") || !dartText.includes("snackbar")) missing.push("interactive core flow markers not found");

if (fs.existsSync(path.join(artifactsDir, "product_score_report.json"))) {
  const score = JSON.parse(fs.readFileSync(path.join(artifactsDir, "product_score_report.json"), "utf8")).score;
  if (Number(score) < 75) missing.push(`quality score below threshold: ${score}`);
}

if (missing.length) {
  console.error(missing.join("\n"));
  process.exit(1);
}

console.log(`Generated app quality checks passed for ${latest}`);
